# This is a basic workflow to help you get started with Actions

name: Android Feature Branch CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: My first step
      if: github.event_name == 'push_request'
      run: echo This event is a push request that had an assignee removed.

