# This is a basic workflow to help you get started with Actions

name: Android Feature Branch CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: master
  pull_request:
    branches: master
    
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk

